# Generated by Django 5.1.2 on 2024-11-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('P_id', models.TextField()),
                ('price', models.TextField()),
                ('offer_price', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('highlights', models.TextField()),
                ('phone', models.BooleanField(default=False)),
                ('dress', models.BooleanField(default=False)),
            ],
        ),
    ]
