# Generated by Django 5.1.2 on 2025-01-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_buy_product_remove_cart_product_buy_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='categorys',
            name='offer_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='categorys',
            name='price',
            field=models.IntegerField(),
        ),
    ]
