# Generated by Django 5.1.2 on 2025-01-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart_quantity_alter_categorys_offer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
