# Generated by Django 5.1.2 on 2025-01-25 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.address'),
        ),
    ]
