# Generated by Django 5.1.4 on 2025-02-14 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.AddField(
            model_name='order',
            name='buy',
            field=models.ForeignKey(default=117, on_delete=django.db.models.deletion.CASCADE, to='app.buy'),
            preserve_default=False,
        ),
    ]
