# Generated by Django 5.1.4 on 2025-02-14 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_order_category_order_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.buy'),
        ),
    ]
