# Generated by Django 5.1.4 on 2025-02-14 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_order_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buy',
        ),
        migrations.AddField(
            model_name='buy',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
    ]
